version: '3.8'

services:
  # Development version with hot reload
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://algohive:algohive123@postgres:5432/algohive_dev
      - REDIS_URL=redis://redis:6379/1
    env_file:
      - .env
      - ./config/environments/development.env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - algohive-network

  # PostgreSQL Database for development
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: algohive_dev
      POSTGRES_USER: algohive
      POSTGRES_PASSWORD: algohive123
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - algohive-network

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - algohive-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  algohive-network:
    driver: bridge