version: '3.8'

services:
  shagun-backend:
    build: .
    container_name: shagun-trading-system
    ports:
      - "8000:8000"
    volumes:
      - shagun-data:/app/data
      - shagun-logs:/app/logs
      - ./live_trading_1000.db:/app/live_trading_1000.db
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./live_trading_1000.db
      - TRADING_MODE=live
      - AUTOMATED_TRADING_ENABLED=true
      - LIVE_TRADING_ENABLED=true
      - MAX_RISK_PER_TRADE=0.05
      - MAX_DAILY_LOSS=0.10
      - DEFAULT_POSITION_SIZE=1000
      - CIRCUIT_BREAKER_ENABLED=true
      - EMERGENCY_STOP_LOSS_AMOUNT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  shagun-data:
    driver: local
  shagun-logs:
    driver: local

networks:
  default:
    name: shagun-network
