apiVersion: v1
kind: ServiceAccount
metadata:
  name: algohive-app
  namespace: algohive

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: algohive-app-role
  namespace: algohive
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: algohive-app-rolebinding
  namespace: algohive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: algohive-app-role
subjects:
  - kind: ServiceAccount
    name: algohive-app
    namespace: algohive