# Note: This is a template. In production, use sealed-secrets or external secret manager
apiVersion: v1
kind: Secret
metadata:
  name: algohive-secrets
  namespace: algohive
type: Opaque
stringData:
  # Database credentials
  DB_USER: "algohive"
  DB_PASSWORD: "changeme"  # Change this in production
  DATABASE_URL: "postgresql://algohive:changeme@postgres-service:5432/algohive"
  
  # Redis password
  REDIS_PASSWORD: "changeme"  # Change this in production
  REDIS_URL: "redis://:changeme@redis-service:6379/0"
  
  # Application secrets
  SECRET_KEY: "your-secret-key-here"  # Generate with: openssl rand -hex 32
  
  # API Keys (encrypted in production)
  KITE_API_KEY: "your-kite-api-key"
  KITE_API_SECRET: "your-kite-api-secret"
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"