name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Shagun Intelligence
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["iamapsrajput"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

        **⚠️ Security Notice**: If this is a security vulnerability, please do not create a public issue. Instead, follow our [Security Policy](https://github.com/iamapsrajput/ShagunIntelligence/blob/main/SECURITY.md).

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/iamapsrajput/ShagunIntelligence/blob/main/CONTRIBUTING.md)
        - label: This is not a security vulnerability (if it is, I will follow the Security Policy)
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "AI Agents (CrewAI)"
        - "API Backend (FastAPI)"
        - "Trading System (Kite Connect)"
        - "Database/ORM (SQLAlchemy)"
        - "Authentication/Security"
        - "WebSocket/Real-time Data"
        - "Docker/Containerization"
        - "Kubernetes/Deployment"
        - "Frontend/Dashboard"
        - "CI/CD Pipeline"
        - "Documentation"
        - "Other"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this issue?
      options:
        - "🔴 Critical (System down, data loss, security breach)"
        - "🟠 High (Major feature broken, significant impact)"
        - "🟡 Medium (Feature partially broken, moderate impact)"
        - "🟢 Low (Minor issue, cosmetic problem)"
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - OS: 
        - Python version: 
        - Docker version: 
        - Browser (if applicable): 
        - Deployment method: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: |
        If applicable, add logs, error messages, or screenshots to help explain your problem.
        
        **⚠️ Important**: Please remove any sensitive information (API keys, personal data, trading details) before pasting logs.
      placeholder: |
        Paste logs here (remember to remove sensitive data)...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...