apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shagunintelligence-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

commonAnnotations:
  environment: staging
  managed-by: kustomize

configMapGenerator:
  - name: shagunintelligence-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - LOG_LEVEL=INFO
      - WORKERS=3
      - MAX_REQUESTS=500

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: shagunintelligence-app
    count: 2
  - name: nginx
    count: 2

images:
  - name: shagunintelligence/app
    newName: ${ECR_REGISTRY}/shagunintelligence
    newTag: staging-latest

# Use external secrets for staging
resources:
  - external-secrets.yaml
